Repository Qiskit/qiskit-aer, pull requests merged in 2020-09, with the labels that each got.

#917 Drop support for Python 3.5
  .travis.yml
  azure-pipelines.yml
  releasenotes/notes/drop-py35-814876e9d7354a39.yaml
  requirements-dev.txt
  setup.py
  tox.ini
Labels: Changelog: Removal

#898 Fix evaluation y expectation
  releasenotes/notes/fix-y-expectation-1ad355c31b4c3247.yaml
  src/simulators/stabilizer/stabilizer_state.hpp
  test/terra/reference/ref_snapshot_expval.py
Labels: Changelog: Bugfix, stable-backport-potential

#913 Fix C++ for-loop by const ref rather than copy
  releasenotes/notes/fix-cpp-for-loop-refs-5a6bb879bf58a4fb.yaml
  src/controllers/qasm_controller.hpp
  src/framework/circuit.hpp
  src/framework/linalg/linops/linops_map.hpp
  src/framework/linalg/linops/linops_unordered_map.hpp
  src/framework/operations.hpp
  src/framework/opset.hpp
  src/framework/utils.hpp
  src/noise/noise_model.hpp
  src/noise/readout_error.hpp
  src/open_pulse/eval_hamiltonian.hpp
  src/open_pulse/log.hpp
  src/open_pulse/test_python_to_cpp.cpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/transpile/delay_measure.hpp
  src/transpile/fusion.hpp
  src/transpile/truncate_qubits.hpp
Labels: stable-backport-potential

#927 Kraus noise gate fusion method
  releasenotes/notes/kraus-noise-fusion-5577d4a38862e966.yaml
  src/controllers/qasm_controller.hpp
  src/framework/noise_utils.hpp
  src/framework/operations.hpp
  src/noise/noise_model.hpp
  src/noise/quantum_error.hpp
  src/transpile/fusion.hpp
  test/terra/backends/qasm_simulator/qasm_fusion.py
  test/terra/backends/test_qasm_simulator_density_matrix.py
Labels: Changelog: New Feature, performance

#918 fix a bug in thread management tests
  test/terra/backends/qasm_simulator/qasm_thread_management.py
Labels: Changelog: Bugfix

#931 Add qobj header global phase support
  releasenotes/notes/global-phase-9fc2105dac076f48.yaml
  src/controllers/qasm_controller.hpp
  src/controllers/statevector_controller.hpp
  src/controllers/unitary_controller.hpp
  src/framework/circuit.hpp
  src/simulators/state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/statevector_simulator/statevector_basics.py
  test/terra/backends/unitary_simulator/unitary_basics.py
Labels: Changelog: New Feature

#932 Add custom Vector class
  releasenotes/notes/vector-class-ee57ad715b18cc55.yaml
  src/controllers/statevector_controller.hpp
  src/framework/linalg/linalg.hpp
  src/framework/linalg/linops/linops_aer_vector.hpp
  src/framework/linalg/square.hpp
  src/framework/linalg/vector.hpp
  src/framework/linalg/vector_json.hpp
  src/framework/pybind_json.hpp
  src/framework/results/experiment_data.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_state.hpp
Labels: Changelog: New Feature, performance

#914 Add support for rotation gates to noise model and simulators
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/noise/noise_model.py
  releasenotes/notes/rotation-gates-7c09f4565329ca78.yaml
  requirements-dev.txt
  src/framework/linalg/matrix_utils.hpp
  src/framework/linalg/matrix_utils/matrix_defs.hpp
  src/framework/linalg/matrix_utils/smatrix_defs.hpp
  src/framework/linalg/matrix_utils/vmatrix_defs.hpp
  src/framework/pybind_json.hpp
  src/framework/utils.hpp
  src/noise/noise_model.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/qasm_simulator/qasm_standard_gates.py
  test/terra/backends/statevector_simulator/statevector_gates.py
  test/terra/backends/test_qasm_simulator.py
  test/terra/backends/test_qasm_simulator_density_matrix.py
  test/terra/backends/test_qasm_simulator_matrix_product_state.py
  test/terra/backends/test_qasm_simulator_statevector.py
  test/terra/backends/test_statevector_simulator.py
  test/terra/backends/test_unitary_simulator.py
  test/terra/backends/unitary_simulator/unitary_gates.py
  test/terra/common.py
  test/terra/pulse/test_system_models.py
Labels: Changelog: New Feature

#945 Make controller_wrapper functions functors
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/backends/wrappers/bindings.cc
  releasenotes/notes/pybind-functors-a0b7b357fbe67dfb.yaml
  src/controllers/controller_execute.hpp
  test/terra/extensions/test_wrappers.py
Labels: Changelog: Bugfix

#948 MPS: Support snapshot_density_matrix
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  test/terra/backends/qasm_simulator/qasm_snapshot.py
  test/terra/backends/test_qasm_simulator_matrix_product_state.py
Labels: Changelog: New Feature

#951 Add support for phase, sqrt(X), and delay gates to simulators
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/noise/noise_model.py
  releasenotes/notes/basis-gates-acbc8a1a52a49413.yaml
  src/framework/linalg/matrix_utils/matrix_defs.hpp
  src/framework/linalg/matrix_utils/smatrix_defs.hpp
  src/framework/linalg/matrix_utils/vmatrix_defs.hpp
  src/noise/noise_model.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/qasm_simulator/qasm_standard_gates.py
  test/terra/backends/statevector_simulator/statevector_gates.py
  test/terra/backends/unitary_simulator/unitary_gates.py
Labels: Changelog: Deprecation, Changelog: New Feature

#915 MPS: Apply kraus
  releasenotes/notes/mps-apply-kraus-3cc8de65a66385ab.yaml
  releasenotes/notes/mps-density-matrix-51f7d5b1ef51e746.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/matrix_product_state/svd.cpp
  test/terra/backends/test_qasm_simulator_matrix_product_state.py
Labels: Changelog: New Feature
