Repository Qiskit/qiskit-aer, pull requests merged in 2020-11, with the labels that each got.

#1003 Fixed bug in MPS::apply_kraus
  releasenotes/notes/kraus-bug-a1940e9b12e40f70.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
Labels: Changelog: Bugfix, stable-backport-potential

#1012 Add PauliGate to density matrix simulator
  qiskit/providers/aer/backends/qasm_simulator.py
  releasenotes/notes/pauli-instruction-c3aa2c0c634e642e.yaml
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_state.hpp
Labels: Changelog: New Feature

#1011 Corrected qubits ordering in MPS::sample_measure_using_probabilities.
  releasenotes/notes/sample_measure-bug-4ce3a1a6553e4900.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
Labels: Changelog: Bugfix, stable-backport-potential

#1028 Fix opset difference
  src/framework/opset.hpp
Labels: stable-backport-potential

#1026 Fixed the tests and the revealed bugs
  qiskit/providers/aer/backends/qasm_simulator.py
  releasenotes/notes/fix-basis-gates-3b5c64c3bbfee1c7.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
  test/terra/backends/qasm_simulator/qasm_standard_gates.py
Labels: Changelog: Bugfix, stable-backport-potential

#859 Switch to using native support for CUDA instead of FindCUDA macros.
  .github/workflows/wheels.yml
  CMakeLists.txt
  cmake/FindPybind11.cmake
  cmake/cython_utils.cmake
  cmake/nvcc_add_compiler_options.cmake
  qiskit/providers/aer/backends/wrappers/CMakeLists.txt
  src/simulators/statevector/qubitvector_thrust.hpp
Labels: build system, stable-backport-potential

#1053 use single shot to find available methods
  qiskit/providers/aer/backends/backend_utils.py
Labels: stable-backport-potential

#1055 Fix bug with nested omp being applied incorrectly
  releasenotes/notes/fix-omp-nested-9d120cd1a08725ab.yaml
  src/controllers/controller.hpp
Labels: stable-backport-potential
