Repository Qiskit/qiskit-aer, pull requests merged in 2020-04, with the labels that each got.

#685 [Stable] 0.4.2 backports
  .travis.yml
  cmake/compiler_utils.cmake
  pyproject.toml
  qiskit/providers/aer/VERSION.txt
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/noise/errors/quantum_error.py
  qiskit/providers/aer/noise/errors/readout_error.py
  requirements-dev.txt
  setup.py
  src/framework/operations.hpp
  src/framework/qobj.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/third-party/linux/lib/muparserx.armv7l.7z
  test/terra/backends/qasm_simulator/qasm_unitary_gate.py
  test/terra/backends/statevector_simulator/statevector_basics.py
  test/terra/backends/test_parameterized_qobj.py
  test/terra/backends/test_qasm_simulator.py
  test/terra/backends/test_qasm_simulator_density_matrix.py
  test/terra/backends/test_qasm_simulator_statevector.py
  test/terra/backends/unitary_simulator/unitary_basics.py
  test/terra/common.py
  test/terra/decorators.py
  test/terra/noise/test_noise_model.py
  test/terra/reference/ref_algorithms.py
  test/terra/reference/ref_diagonal_gate.py
  test/terra/reference/ref_kraus_noise.py
  test/terra/reference/ref_measure.py
  test/terra/reference/ref_pauli_noise.py
  test/terra/reference/ref_reset_noise.py
  test/terra/reference/ref_snapshot_expval.py
  tools/verify_wheels.py
Labels: Changelog: Bugfix

#695 Avoid to_dict() when possible in pulse system model
  qiskit/providers/aer/pulse/pulse_system_model.py
Labels: stable-backport-potential

#693 Fix ReduceBarriers to be applied before qubit truncation
  src/controllers/controller.hpp
  src/controllers/qasm_controller.hpp
Labels: stable-backport-potential

#688 Disable jsonschema validation by default
  qiskit/providers/aer/backends/aerbackend.py
  qiskit/providers/aer/releasenotes/notes/validation-opt-in-e43a002f160ddd11.yaml
Labels: Changelog: API Change, stable-backport-potential

#691 Refactor circuit
  src/framework/circuit.hpp
  src/framework/qobj.hpp
  src/noise/noise_model.hpp
Labels: stable-backport-potential

#699 Remove "extended_stabilizer" from automatic simulation methods.
  releasenotes/notes/automatic-method-930a74f765b9a94c.yaml
  src/controllers/qasm_controller.hpp
Labels: Changelog: API Change, stable-backport-potential

#701 adding cy to stabilizer
  src/simulators/stabilizer/stabilizer_state.hpp
Labels: stable-backport-potential

#697 Pybind numpy input
  src/framework/pybind_json.hpp
  test/terra/backends/qasm_simulator/qasm_initialize.py
  test/terra/backends/qasm_simulator/qasm_unitary_gate.py
  test/terra/reference/ref_diagonal_gate.py
  test/terra/reference/ref_initialize.py
Labels: stable-backport-potential

#698 Update transpilation pass interface in controller
  releasenotes/notes/controller-transpile-298ea8d76a406648.yaml
  src/controllers/controller.hpp
  src/controllers/qasm_controller.hpp
  src/transpile/fusion.hpp
  test/terra/backends/qasm_simulator/qasm_fusion.py
Labels: stable-backport-potential

#704 Fix depol error param for device noise model with depol + relaxation error
  qiskit/providers/aer/noise/device/basic_device_model.py
  qiskit/providers/aer/noise/device/models.py
  qiskit/providers/aer/noise/device/parameters.py
  qiskit/providers/aer/noise/errors/quantum_error.py
  qiskit/providers/aer/noise/noise_model.py
  releasenotes/notes/device-errors-bb231623712ecda7.yaml
Labels: stable-backport-potential

#706 Add missing release notes
  releasenotes/notes/fix-reduce-barrier-7b1dfeb4a9389516.yaml
  releasenotes/notes/stabilizer-cy-200773f25da609d3.yaml
Labels: stable-backport-potential

#707 Fix tolerance when checking if diagonal is unitary
  releasenotes/notes/fix-diagonal-unitary-check-a726500ffda6c74b.yaml
  src/framework/operations.hpp
  test/terra/backends/qasm_simulator/qasm_unitary_gate.py
  test/terra/reference/ref_diagonal_gate.py
Labels: stable-backport-potential
