Repository Qiskit/qiskit-aer, pull requests merged in 2020-06, with the labels that each got.

#763 Fix required memory checks for QasmSimulator with custom method
  releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml
  src/controllers/controller.hpp
  src/controllers/qasm_controller.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/statevector/statevector_state.hpp
Labels: Changelog: Bugfix, stable-backport-potential

#771 Fix bug in DensityMatrixThrust apply_y
  src/simulators/density_matrix/densitymatrix_thrust.hpp
Labels: stable-backport-potential

#475 Introducing approximation into the MPS simulation method
  qiskit/providers/aer/backends/qasm_simulator.py
  releasenotes/notes/mps-approximation-5139ae07accea25f.yaml
  src/controllers/qasm_controller.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
  src/simulators/matrix_product_state/svd.cpp
  src/simulators/matrix_product_state/svd.hpp
  src/simulators/state.hpp
Labels: Changelog: New Feature

#799 Improve performance of pybind11 result conversion
  releasenotes/notes/pybind11-094ae708e4358523.yaml
  src/framework/pybind_json.hpp
  src/framework/results/experiment_data.hpp
Labels: performance

#796 Remove unnecessary copy of ExperimentResult objects
  src/controllers/controller.hpp
  src/controllers/qasm_controller.hpp
  src/controllers/statevector_controller.hpp
  src/controllers/unitary_controller.hpp
  src/framework/matrix.hpp
  src/framework/results/data/data_container.hpp
  src/framework/results/data/pershot_data.hpp
Labels: performance

#807 Improve performance of average snapshots
  contrib/standalone/qasm_simulator.cpp
  releasenotes/notes/improve-ave-snapshots-768767618ff00c2d.yaml
  src/controllers/controller_execute.hpp
  src/framework/results/data/average_data.hpp
  src/framework/results/data/average_snapshot.hpp
  src/framework/results/data/data_container.hpp
  src/framework/results/data/pershot_data.hpp
  src/framework/results/data/pershot_snapshot.hpp
  src/framework/results/experiment_data.hpp
  src/framework/results/experiment_result.hpp
  src/framework/results/result.hpp
Labels: performance
