Repository Qiskit/qiskit-aer, pull requests merged in 2021-02, with the labels that each got.

#788 Parallel Qiskit Aer (GPU + MPI) by using cache blocking transpiler
  CMakeLists.txt
  CONTRIBUTING.md
  Makefile.Thrust
  contrib/standalone/qasm_simulator.cpp
  qiskit/providers/aer/backends/wrappers/bindings.cc
  src/controllers/controller.hpp
  src/controllers/qasm_controller.hpp
  src/controllers/statevector_controller.hpp
  src/controllers/unitary_controller.hpp
  src/framework/operations.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_state_chunk.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/chunk/chunk.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/chunk_manager.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/host_chunk_container.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/statevector/statevector_state_chunk.hpp
  src/simulators/unitary/unitary_state.hpp
  src/simulators/unitary/unitary_state_chunk.hpp
  src/simulators/unitary/unitarymatrix.hpp
  src/simulators/unitary/unitarymatrix_thrust.hpp
  src/transpile/cacheblocking.hpp
  src/transpile/truncate_qubits.hpp
  test/terra/backends/qasm_simulator/qasm_mpi.py
  test/terra/backends/test_qasm_simulator_density_matrix_mpi.py
  test/terra/backends/test_qasm_simulator_statevector_mpi.py
  test/terra/decorators.py
Labels: Changelog: New Feature

#1116 Add ``SaveStatevector`` and ``SaveDensityMatrix`` instructions
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/save_data.py
  qiskit/providers/aer/library/save_density_matrix.py
  qiskit/providers/aer/library/save_expectation_value.py
  qiskit/providers/aer/library/save_statevector.py
  releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
  src/framework/operations.hpp
  src/framework/results/data/data.hpp
  src/framework/results/data/mixins/data_cdict.hpp
  src/framework/results/data/mixins/data_cmatrix.hpp
  src/framework/results/data/mixins/data_cvector.hpp
  src/framework/results/data/mixins/pybind_data_cdict.hpp
  src/framework/results/data/mixins/pybind_data_cmatrix.hpp
  src/framework/results/data/mixins/pybind_data_cvector.hpp
  src/framework/results/data/pybind_data.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/extended_stabilizer/ch_runner.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/state.hpp
  src/simulators/statevector/statevector_state.hpp
  test/terra/backends/qasm_simulator/qasm_save.py
  test/terra/backends/qasm_simulator/qasm_save_density_matrix.py
  test/terra/backends/qasm_simulator/qasm_save_expval.py
  test/terra/backends/qasm_simulator/qasm_save_statevector.py
Labels: Changelog: API Change, Changelog: New Feature

#1117 Add `SaveProbabilities` and `SaveProbabilitiesDict` instructions
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/save_probabilities.py
  releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
  src/framework/operations.hpp
  src/framework/results/data/data.hpp
  src/framework/results/data/mixins/data_rdict.hpp
  src/framework/results/data/mixins/pybind_data_rdict.hpp
  src/framework/results/data/pybind_data.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/statevector_state.hpp
  test/terra/backends/qasm_simulator/qasm_save.py
  test/terra/backends/qasm_simulator/qasm_save_probabilities.py
Labels: Changelog: New Feature

#1129 Add `SaveAmplitudes` and `SaveAmplitudesSquared` instructions.
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/extensions/snapshot_amplitudes.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/save_amplitudes.py
  releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
  releasenotes/notes/snapshot_amplitudes-c2be90ac2830517e.yaml
  src/framework/operations.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/statevector_state.hpp
  test/terra/backends/qasm_simulator/qasm_save.py
  test/terra/backends/qasm_simulator/qasm_save_amplitudes.py
  test/terra/backends/qasm_simulator/qasm_snapshot.py
  test/terra/backends/test_qasm_simulator_matrix_product_state.py
  test/terra/extensions/test_save_amplitudes.py
  test/terra/extensions/test_snapshot_amplitudes.py
  test/terra/reference/ref_snapshot_amplitudes.py
Labels: Changelog: New Feature

#1137 Migrate windows CI to all be in github actions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/tests_windows.yml
  azure-pipelines.yml
  pyproject.toml
Labels: build system

#1139 Add _directive attr to Save instruction
  qiskit/providers/aer/extensions/snapshot.py
  qiskit/providers/aer/library/save_data.py
Labels: on hold

#1136 Add SaveUnitary and SaveStabilizer instructions
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/save_stabilizer.py
  qiskit/providers/aer/library/save_unitary.py
  releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
  src/framework/operations.hpp
  src/framework/results/data/data.hpp
  src/framework/results/data/mixins/data_json.hpp
  src/framework/results/data/mixins/pybind_data_json.hpp
  src/framework/results/data/pybind_data.hpp
  src/simulators/stabilizer/clifford.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/qasm_simulator/qasm_save.py
  test/terra/backends/qasm_simulator/qasm_save_stabilizer.py
  test/terra/backends/test_unitary_simulator.py
  test/terra/backends/unitary_simulator/unitary_save.py
Labels: Changelog: New Feature

#1154 Fix noise sampling for conditional gates
  releasenotes/notes/fix-conditional-noise-178f5d03b97a8dd5.yaml
  src/noise/noise_model.hpp
  test/terra/reference/ref_pauli_noise.py
Labels: Changelog: Bugfix, stable-backport-potential

#1152 change default max_memory_mb from half to full system memory
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  src/controllers/controller.hpp
Labels: Changelog: Bugfix, stable-backport-potential
