Repository Qiskit/qiskit-aer, pull requests merged in 2021-01, with the labels that each got.

#1089 Fix condtional instructions using `c_if` not working for reg of size>=64 on BasicAer backend
  releasenotes/notes/fix-c-if-large-register-79d6649395e57ff5.yaml
  src/framework/creg.hpp
  src/framework/utils.hpp
  test/terra/backends/qasm_simulator/qasm_conditional.py
  test/terra/backends/statevector_simulator/statevector_basics.py
  test/terra/reference/ref_conditionals.py
Labels: Changelog: Bugfix

#1094 Fixed normalization in MPS truncation
  releasenotes/notes/fix-truncation-85010290548c2d16.yaml
  src/simulators/matrix_product_state/svd.cpp
Labels: Changelog: Bugfix

#1108 Fix noise model basis_gates when constructing from device
  qiskit/providers/aer/noise/noise_model.py
  releasenotes/notes/fix-noise-basis-gates-ecdfa43394ff78e3.yaml
Labels: Changelog: Bugfix, stable-backport-potential

#1109 Fix bugs in automatic updates of simulator configuration basis gates
  qiskit/providers/aer/backends/qasm_simulator.py
  releasenotes/notes/fix-backend-noise-model-f22e9d6254d70852.yaml
  test/terra/backends/qasm_simulator/qasm_method.py
Labels: Changelog: Bugfix, stable-backport-potential

#1112 Add Windows Python 3.9 release wheel builds
  azure-pipelines.yml
Labels: stable-backport-potential
