Repository Qiskit/qiskit-aer, pull requests merged in 2021-03, with the labels that each got.

#1132 Fixed bug in sample_measure_using_probabilities
  releasenotes/notes/issue1126-e2d51f660b0078db.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  test/terra/reference/ref_measure.py
Labels: Changelog: Bugfix, stable-backport-potential

#1175 Fix extended stabilizer method basis gates
  qiskit/providers/aer/backends/qasm_simulator.py
Labels: stable-backport-potential

#1164 Add general SaveState instruction
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/save_state.py
  releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
  src/framework/operations.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_state_chunk.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/statevector/statevector_state_chunk.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/qasm_simulator/qasm_save.py
  test/terra/backends/qasm_simulator/qasm_save_state.py
Labels: Changelog: New Feature

#1187 Always set config.local to True
  qiskit/providers/aer/backends/aerbackend.py
  releasenotes/notes/config-local-46d47ae08eeab339.yaml
  test/terra/backends/test_config_pulse_simulator.py
Labels: Changelog: Bugfix, stable-backport-potential

#1099 Migrate to new provider interface
  qiskit/providers/aer/aerjob.py
  qiskit/providers/aer/aerprovider.py
  qiskit/providers/aer/backends/aerbackend.py
  qiskit/providers/aer/backends/pulse_simulator.py
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/pulse/controllers/pulse_controller.py
  releasenotes/notes/add-new-backend-interface-5d8c1b5c7d47c50c.yaml
  test/terra/backends/qasm_simulator/qasm_algorithms.py
  test/terra/backends/qasm_simulator/qasm_cliffords.py
  test/terra/backends/qasm_simulator/qasm_method.py
  test/terra/backends/statevector_simulator/statevector_basics.py
  test/terra/backends/test_pulse_simulator.py
  test/terra/backends/unitary_simulator/unitary_basics.py
  tools/verify_wheels.py
Labels: Changelog: New Feature

#1163 Add instructions to set simulator state
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
  qiskit/providers/aer/library/__init__.py
  qiskit/providers/aer/library/default_qubits.py
  qiskit/providers/aer/library/save_instructions/__init__.py
  qiskit/providers/aer/library/save_instructions/save_amplitudes.py
  qiskit/providers/aer/library/save_instructions/save_data.py
  qiskit/providers/aer/library/save_instructions/save_density_matrix.py
  qiskit/providers/aer/library/save_instructions/save_expectation_value.py
  qiskit/providers/aer/library/save_instructions/save_matrix_product_state.py
  qiskit/providers/aer/library/save_instructions/save_probabilities.py
  qiskit/providers/aer/library/save_instructions/save_stabilizer.py
  qiskit/providers/aer/library/save_instructions/save_state.py
  qiskit/providers/aer/library/save_instructions/save_statevector.py
  qiskit/providers/aer/library/save_instructions/save_unitary.py
  qiskit/providers/aer/library/set_instructions/__init__.py
  qiskit/providers/aer/library/set_instructions/set_density_matrix.py
  qiskit/providers/aer/library/set_instructions/set_stabilizer.py
  qiskit/providers/aer/library/set_instructions/set_statevector.py
  qiskit/providers/aer/library/set_instructions/set_unitary.py
  releasenotes/notes/0.5/validation-opt-in-e43a002f160ddd11.yaml
  releasenotes/notes/set-state-a029d86b357df0dd.yaml
  src/framework/operations.hpp
  src/framework/types.hpp
  src/framework/utils.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/simulators/unitary/unitarymatrix.hpp
  src/simulators/unitary/unitarymatrix_thrust.hpp
  test/terra/backends/qasm_simulator/qasm_set_state.py
  test/terra/backends/test_qasm_simulator.py
  test/terra/backends/test_qasm_simulator_density_matrix.py
  test/terra/backends/test_qasm_simulator_stabilizer.py
  test/terra/backends/test_qasm_simulator_statevector.py
Labels: Changelog: New Feature
