Repository Qiskit/qiskit-aer, pull requests merged in 2021-11, with the labels that each got.

#1380 Include pyproject.toml in sdist
  MANIFEST.in
Labels: stable-backport-potential, Changelog: Bugfix

#1382 Fix deprecated qiskit.util imports
  qiskit/providers/aer/backends/backend_utils.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/backends/unitary_simulator.py
Labels: stable-backport-potential

#1350 Add support for adding QuantumError to circuits
  qiskit/providers/aer/backends/aer_simulator.py
  qiskit/providers/aer/backends/aerbackend.py
  qiskit/providers/aer/backends/backend_utils.py
  qiskit/providers/aer/backends/qasm_simulator.py
  qiskit/providers/aer/backends/statevector_simulator.py
  qiskit/providers/aer/noise/errors/quantum_error.py
  qiskit/providers/aer/noise/noise_model.py
  qiskit/providers/aer/utils/noise_transformation.py
  releasenotes/notes/circ_errors-b3c815bc1db48066.yaml
  src/framework/operations.hpp
  src/noise/noise_model.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_state_chunk.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/statevector/statevector_state_chunk.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/simulators/unitary/unitary_state_chunk.hpp
  test/terra/backends/aer_simulator/test_noise.py
  test/terra/noise/test_noise_inserter.py
  test/terra/noise/test_standard_errors.py
Labels: Changelog: New Feature
