Repository Qiskit/qiskit-aer, pull requests merged in 2022-03, with the labels that each got.

#1469 Do not build with `-ffast-math`
  CMakeLists.txt
  releasenotes/notes/no-fast-math-1de357a9650094f3.yaml
  src/simulators/extended_stabilizer/ch_runner.hpp
Labels: stable-backport-potential, Changelog: API Change, Changelog: Bugfix

#1472 Split out gpu Python 3.10 wheel build
  .github/workflows/deploy.yml
Labels: stable-backport-potential

#1467 Change to truncate T2 up to 2 * T1 in NoiseModel.from_backend
  qiskit/providers/aer/noise/device/models.py
  qiskit/providers/aer/noise/device/parameters.py
  qiskit/providers/aer/noise/noise_model.py
  releasenotes/notes/fix-invalid-t2-error-a3685e4a3ad0a1e7.yaml
  test/terra/noise/test_noise_model.py
Labels: Changelog: Bugfix

#1480 Fix: cache blocking transpiler for density_matrix with noises
  releasenotes/notes/density-multi-chunk-fix-e9effc67d0365418.yaml
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_state.hpp
  src/transpile/cacheblocking.hpp
  test/terra/backends/aer_simulator/test_chunk.py
  test/terra/backends/aer_simulator/test_noise.py
Labels: stable-backport-potential

#1490 Pin jinja2 in CI
  constraints.txt
Labels: stable-backport-potential

#1482 Fix for GPU batched optimization with Pauli noise
  qiskit/providers/aer/backends/aer_simulator.py
  releasenotes/notes/multi-shots-pauli-noise-improvements-87637a02e81806cf.yaml
  src/controllers/aer_controller.hpp
  src/framework/utils.hpp
  src/noise/noise_model.hpp
  src/noise/quantum_error.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/chunk_manager.hpp
  src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
  src/simulators/statevector/chunk/cuda_kernels.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/host_chunk_container.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
Labels: stable-backport-potential

#1495 Fix 1487 by correcting documentation
  qiskit/providers/aer/noise/device/parameters.py
Labels: documentation

#1436 Fix handling of circuit metadata
  qiskit/providers/aer/backends/aerbackend.py
  releasenotes/notes/remove_circuit_metadata_from_qobj-324e7ea9b369ee67.yaml
  test/terra/backends/aer_simulator/test_metadata.py
Labels: stable-backport-potential, Changelog: Bugfix
