Repository Qiskit/qiskit-aer, pull requests merged in 2022-08, with the labels that each got.

#1570 Avoid using inversed isometry gate in multiplexer test
  test/terra/reference/ref_multiplexer.py
Labels: Changelog: None, automerge

#1569 Fix for save_statevector and fix for global indexing for Thrust
  CONTRIBUTING.md
  releasenotes/notes/MPI_chunk_fixes-1ea74548cd3c3515.yaml
  src/simulators/state_chunk.hpp
  src/transpile/cacheblocking.hpp
Labels: automerge

#1566 Sphinx warning box broken in `QuantumError` docstring
  qiskit/providers/aer/noise/errors/quantum_error.py
Labels: documentation, automerge

#1582 Add libaer.so
  CMakeLists.txt
  contrib/runtime/aer_runtime.cpp
  contrib/runtime/aer_runtime_api.h
  releasenotes/notes/add_aer_runtime_library-6a0efd6a75a510b9.yaml
  src/controllers/aer_controller.hpp
  src/controllers/state_controller.hpp
  src/framework/pybind_basics.hpp
  src/framework/results/experiment_result.hpp
  src/misc/common_macros.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/runtime/runtime_sample.c
Labels: Changelog: New Feature, automerge
