Repository Qiskit/qiskit-aer, pull requests merged in 2022-11, with the labels that each got.

#1634 Fix cache_blocking transpiler to restore qubit map for AerState
  releasenotes/notes/fix_cache_blocking_AerState-ccb035bb5be6f895.yaml
  src/controllers/state_controller.hpp
  src/transpile/cacheblocking.hpp
Labels: stable-backport-potential

#1639 Remove verbose warnings on parameter truncations when creating noise model from backend
  qiskit_aer/noise/device/models.py
  qiskit_aer/noise/noise_model.py
  releasenotes/notes/fix-vervose-warnings-efbbbfcb4b65a2a5.yaml
  test/terra/noise/test_noise_model.py
Labels: stable-backport-potential, Changelog: Bugfix

#1650 Fix for GPU simulator, memory allocation
  releasenotes/notes/fix_GPU_statevector-715da5ead0a59fb5.yaml
  src/controllers/aer_controller.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
Labels: stable-backport-potential

#1654 Remove unnecessary transpile in Estimator
  qiskit_aer/primitives/estimator.py
Labels: stable-backport-potential, automerge

#1642 Add support for Python 3.11
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  pyproject.toml
  releasenotes/notes/add-python-311-support-027047fb389116dd.yaml
  requirements-dev.txt
  setup.py
  tools/install_openblas_i686.sh
  tox.ini
Labels: stable-backport-potential, Changelog: New Feature

#1666 Fix data-flow analysis in control-flow jump/mark
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/library/control_flow_instructions/jump.py
  qiskit_aer/library/control_flow_instructions/mark.py
  releasenotes/notes/fix-topological-control-flow-e2f1a25098004f00.yaml
  test/terra/backends/aer_simulator/test_control_flow.py
Labels: stable-backport-potential, Changelog: Bugfix

#1670 Fix SamplerResult num_clbits
  qiskit_aer/primitives/sampler.py
  releasenotes/notes/sampler-counts-90e5aaabccdc415b.yaml
  test/terra/primitives/test_sampler.py
Labels: stable-backport-potential

#1644 Support for initialization from Statevector
  qiskit_aer/quantum_info/states/aer_statevector.py
  releasenotes/notes/improve-statevector-initialization-75274fdcb4106d24.yaml
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential

#1649 Fix device noise model from BackendV2 not to have excessive quantum errors on measures/resets
  qiskit_aer/noise/device/models.py
  releasenotes/notes/fix-device-noise-models-2eca2f9c9dc25771.yaml
  test/terra/noise/test_device_models.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#1643 Use more gates for AerState to call state_controller
  contrib/runtime/aer_runtime.cpp
  qiskit_aer/backends/wrappers/bindings.cc
  qiskit_aer/quantum_info/states/aer_state.py
  qiskit_aer/quantum_info/states/aer_statevector.py
  releasenotes/notes/fix_aer_statevector_mps-c3dd40b936700ff4.yaml
  src/controllers/state_controller.hpp
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential
