Repository Qiskit/qiskit-aer, pull requests merged in 2022-06, with the labels that each got.

#1536 Make CI to build OpenMP from source through conan for mac
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  cmake/conan_utils.cmake
Labels: MacOS, build system, stable-backport-potential, Changelog: None

#1535 Removing usage of the deprecated U1Gate from parallel processing examples.
  docs/apidocs/parallel.rst
Labels: Changelog: None, automerge

#1542 Add qiskit-sphinx-theme to tutorial job
  .github/workflows/docs.yml
Labels: Changelog: None, automerge

#1538 fix issues from mismatch of binding specs in assemble and backend of aer
  qiskit/providers/aer/backends/aerbackend.py
  test/terra/backends/test_parameterized_qobj.py
Labels: bug, stable-backport-potential, automerge

#1541 Add qiskit-neko integration test job
  .github/workflows/neko.yml
Labels: Changelog: None, automerge

#1548 Set Sphinx language to explicitly English
  docs/conf.py
Labels: Changelog: None, automerge

#1546 Remove distutils import per PEP 632
  qiskit/providers/aer/pulse/__init__.py
Labels: automerge

#1547 Remove deprecated use of `qiskit.test.mock`
  releasenotes/notes/terra-version-bump-68eac37136428805.yaml
  setup.py
  test/terra/backends/test_config_pulse_simulator.py
  test/terra/backends/test_pulse_simulator.py
  test/terra/pulse/test_system_models.py
Labels: automerge
