Repository Qiskit/qiskit-aer, pull requests merged in 2022-07, with the labels that each got.

#1550 Use qiskit.providers.fake_provider instead of qiskit.test.mock and correct rccx and rcccx usages in tests
  test/terra/backends/aer_simulator/test_standard_gates.py
  test/terra/backends/aer_simulator/test_truncate.py
  test/terra/noise/test_noise_model.py
Labels: Changelog: None, automerge

#1504 Add cross-build wheel jobs for ppc64le and s390x
  .github/workflows/deploy.yml
  releasenotes/notes/non-x86_ibm_cpu-493e51313ba222a6.yaml
Labels: Changelog: New Feature

#1531 Add primitives (Sampler and Estimator)
  .pylintrc
  docs/apidocs/aer.rst
  docs/apidocs/aer_primitives.rst
  qiskit/providers/aer/primitives/__init__.py
  qiskit/providers/aer/primitives/estimator.py
  qiskit/providers/aer/primitives/sampler.py
  releasenotes/notes/add-primitives-65bf67ea8f0c29b1.yaml
  test/terra/primitives/__init__.py
  test/terra/primitives/test_estimator.py
  test/terra/primitives/test_sampler.py
Labels: enhancement
