Repository Qiskit/qiskit-aer, pull requests merged in 2022-02, with the labels that each got.

#1422 Fix diagonal fusion in parallel transpilations
  releasenotes/notes/fix_parallel_diag_fusion-a7f914b3a9f491f7.yaml
  src/transpile/fusion.hpp
  test/terra/backends/aer_simulator/test_fusion.py
Labels: stable-backport-potential, Changelog: Bugfix

#1434 Add support for Python 3.10
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/tests_linux.yml
  .github/workflows/tests_mac.yml
  .github/workflows/tests_windows.yml
  releasenotes/notes/add-py310-b6b1e7a0ed3a8e9d.yaml
  setup.py
  tox.ini
Labels: stable-backport-potential, Changelog: New Feature

#1448 Simplify Aer CI configuration
  .github/workflows/tests.yml
  .github/workflows/tests_mac.yml
  .github/workflows/tests_windows.yml
Labels: stable-backport-potential

#1428 Run truncation after resolving parameters
  releasenotes/notes/resolve_parameters_before_truncation-ec7074f1f0f831e2.yaml
  src/framework/qobj.hpp
  test/terra/backends/test_parameterized_qobj.py
Labels: stable-backport-potential, Changelog: Bugfix

#1454 Fix unit handling in RelaxationNoisePass
  qiskit/providers/aer/noise/passes/relaxation_noise_pass.py
  releasenotes/notes/delay-pass-units-a31341568057fdb3.yaml
  test/terra/noise/passes/test_relaxation_noise_pass.py
Labels: stable-backport-potential, Changelog: Bugfix

#1455 Fix LocalNoisePass for circuit returns from noise func
  qiskit/providers/aer/noise/passes/local_noise_pass.py
  releasenotes/notes/fix-local-noise-pass-f94546869a169103.yaml
  test/terra/noise/passes/test_local_noise_pass.py
Labels: stable-backport-potential, Changelog: Bugfix

#1438 fix performance regression produced by #1392
  src/simulators/statevector/qv_avx2.cpp
Labels: stable-backport-potential, Changelog: Bugfix

#1437 Fix time_taken value in cluster backend
  qiskit/providers/aer/jobs/aerjobset.py
  test/terra/backends/aer_simulator/test_executors.py
Labels: stable-backport-potential, Changelog: Bugfix

#1449 Only install numpy and scipy from wheels in build jobs
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  pyproject.toml
Labels: stable-backport-potential

#1430 Drop support for Python 3.6
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  pyproject.toml
  releasenotes/notes/drop-python36-61553302523fa240.yaml
  setup.py
  tox.ini
Labels: Changelog: Removal
