Repository Qiskit/qiskit-aer, pull requests merged in 2022-10, with the labels that each got.

#1613 Fix CMakeList.txt to support build GPU with cmake 3.18 or later
  CMakeLists.txt
  qiskit_aer/backends/wrappers/CMakeLists.txt
  releasenotes/notes/cmake_cuda_arch-817eb0b7232bd291.yaml
Labels: stable-backport-potential, automerge

#1598 Primitives support run method in Terra 0.22
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
  requirements-dev.txt
  test/terra/decorators.py
  test/terra/primitives/test_estimator.py
  test/terra/primitives/test_sampler.py
Labels: stable-backport-potential

#1621 Use AerStatevector in unittests
  qiskit_aer/quantum_info/states/aer_statevector.py
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential, automerge

#1627 Update pip install command to reference qiskit-aer
  README.md
Labels: documentation, stable-backport-potential, Changelog: None, automerge

#1628 add release note for #1598 that supports Primitive of Terra 0.22
  releasenotes/notes/support_terra_primitive_022-8852b784608bcdcb.yaml
Labels: documentation, stable-backport-potential, automerge

#1626 Release 0.11.1
  .github/workflows/deploy.yml
  CMakeLists.txt
  README.md
  docs/conf.py
  qiskit_aer/VERSION.txt
  qiskit_aer/backends/wrappers/CMakeLists.txt
  qiskit_aer/noise/passes/local_noise_pass.py
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
  qiskit_aer/quantum_info/states/aer_statevector.py
  releasenotes/config.yaml
  releasenotes/notes/0.11/fix-for-loop-no-parameter-aa5b04b1da0e956b.yaml
  releasenotes/notes/0.11/support_initialize_with_label-bc08f29928d3e3f3.yaml
  releasenotes/notes/cmake_cuda_arch-817eb0b7232bd291.yaml
  releasenotes/notes/fix-local-noise-pass-83815d5a80f9a0e9.yaml
  releasenotes/notes/sampler-cache-78f916cedb0c5421.yaml
  releasenotes/notes/support_terra_primitive_022-8852b784608bcdcb.yaml
  src/controllers/aer_controller.hpp
  test/terra/decorators.py
  test/terra/noise/passes/test_local_noise_pass.py
  test/terra/primitives/test_estimator.py
  test/terra/primitives/test_sampler.py
  test/terra/states/test_aer_statevector.py
Labels: on hold, Changelog: None
