Repository Qiskit/qiskit-aer, pull requests merged in 2022-09, with the labels that each got.

#1588 Enhancement of Sampler shots is None
  qiskit_aer/primitives/sampler.py
  test/terra/primitives/test_sampler.py
Labels: automerge

#1593 Add release note for namespace migration
  releasenotes/notes/new-namespace-9c3b9fd73ed504e6.yaml
Labels: Changelog: None, automerge

#1591 remove snapshot instruction from qiskit_aer
  docs/apidocs/aer.rst
  docs/apidocs/aer_extensions.rst
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/extensions/__init__.py
  qiskit_aer/extensions/snapshot.py
  qiskit_aer/extensions/snapshot_density_matrix.py
  qiskit_aer/extensions/snapshot_expectation_value.py
  qiskit_aer/extensions/snapshot_probabilities.py
  qiskit_aer/extensions/snapshot_stabilizer.py
  qiskit_aer/extensions/snapshot_statevector.py
  qiskit_aer/jobs/utils.py
  releasenotes/notes/remove_snapsho_operations-a78f13f23c7743b6.yaml
  test/terra/extensions/test_snapshot_density_matrix.py
  test/terra/extensions/test_snapshot_expectation_value.py
  test/terra/extensions/test_snapshot_probabilities.py
  test/terra/extensions/test_snapshot_stabilizer.py
  test/terra/extensions/test_snapshot_statevector.py
Labels: Changelog: Removal, automerge

#1586 Add AerState that allows python access simulator state directly
  qiskit_aer/backends/wrappers/bindings.cc
  qiskit_aer/quantum_info/__init__.py
  qiskit_aer/quantum_info/states/__init__.py
  qiskit_aer/quantum_info/states/aer_state.py
  src/controllers/state_controller.hpp
  src/framework/linalg/vector.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/runtime/runtime_sample.c
  test/terra/states/test_aer_state.py
Labels: Changelog: None, automerge

#1597 Revert "Primitives support Terra 0.22 (#1578)"
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
Labels: automerge

#1600 fix an issue of while_loop at the tail of a circuit
  releasenotes/notes/fix_bug_in_tail_while-6a9201d1ad6ba6e8.yaml
  src/framework/circuit.hpp
  test/terra/backends/aer_simulator/test_control_flow.py
Labels: Changelog: Bugfix, automerge

#1601 Prepare 0.11.0 release
  releasenotes/notes/0.11/MPI-chunk-swap-optimization-8e693483ed271583.yaml
  releasenotes/notes/0.11/MPI_chunk_fixes-1ea74548cd3c3515.yaml
  releasenotes/notes/0.11/add-backendv2-support-to-noise-model-78fe515040918793.yaml
  releasenotes/notes/0.11/add-primitives-65bf67ea8f0c29b1.yaml
  releasenotes/notes/0.11/add_aer_runtime_library-6a0efd6a75a510b9.yaml
  releasenotes/notes/0.11/allow_multiplexer_without_control_qubits-f5cb8bdbe6302e55.yaml
  releasenotes/notes/0.11/arm64-macos-wheels-3778e83a8d036168.yaml
  releasenotes/notes/0.11/change_default_fusion_parameters-cec337a003208e06.yaml
  releasenotes/notes/0.11/config.yaml
  releasenotes/notes/0.11/cuQuantum-support-d33abe5b1cb778a8.yaml
  releasenotes/notes/0.11/cuQuantum_22.05.0.41_support-cb0e797b57d20c3a.yaml
  releasenotes/notes/0.11/delay-pass-units-a31341568057fdb3.yaml
  releasenotes/notes/0.11/drop-python36-61553302523fa240.yaml
  releasenotes/notes/0.11/fix-for-loop-no-parameter-aa5b04b1da0e956b.yaml
  releasenotes/notes/0.11/fix-invalid-t2-error-a3685e4a3ad0a1e7.yaml
  releasenotes/notes/0.11/fix-qerror-assemble-9919a93b210ca776.yaml
  releasenotes/notes/0.11/fix-seed-generation-MPI-ee1f0ad44e913d4f.yaml
  releasenotes/notes/0.11/fix_MPI_distribution-23cdf0d15258816f.yaml
  releasenotes/notes/0.11/fix_cacheblocking__multi_control_gates-f6a7fca4f3db2f61.yaml
  releasenotes/notes/0.11/fix_qerror_to_dict-13a7683ac4adddd4.yaml
  releasenotes/notes/0.11/make_random_seed_reproducible-a7abdfc09ec67bd8.yaml
  releasenotes/notes/0.11/multi-shots-pauli-noise-improvements-87637a02e81806cf.yaml
  releasenotes/notes/0.11/new-namespace-9c3b9fd73ed504e6.yaml
  releasenotes/notes/0.11/non-x86_ibm_cpu-493e51313ba222a6.yaml
  releasenotes/notes/0.11/prepare-0.11-63503170f57ab66d.yaml
  releasenotes/notes/0.11/remove_snapsho_operations-a78f13f23c7743b6.yaml
  releasenotes/notes/0.11/support_for_cuQuantum0.40-566391cc42be2341.yaml
  releasenotes/notes/0.11/support_initialize_with_label-bc08f29928d3e3f3.yaml
  releasenotes/notes/0.11/terra-version-bump-68eac37136428805.yaml
  releasenotes/notes/add-backendv2-support-to-noise-model-78fe515040918793.yaml
  releasenotes/notes/add-primitives-65bf67ea8f0c29b1.yaml
  releasenotes/notes/add-py310-b6b1e7a0ed3a8e9d.yaml
  releasenotes/notes/add_aer_runtime_library-6a0efd6a75a510b9.yaml
  releasenotes/notes/change_default_fusion_parameters-cec337a003208e06.yaml
  releasenotes/notes/density-multi-chunk-fix-e9effc67d0365418.yaml
  releasenotes/notes/fix-local-noise-pass-f94546869a169103.yaml
  releasenotes/notes/fix-thrust-cpu-threads-67db86b2edcf06b3.yaml
  releasenotes/notes/fix_parallel_diag_fusion-a7f914b3a9f491f7.yaml
  releasenotes/notes/no-fast-math-1de357a9650094f3.yaml
  releasenotes/notes/remove_circuit_metadata_from_qobj-324e7ea9b369ee67.yaml
  releasenotes/notes/resolve_parameters_before_truncation-ec7074f1f0f831e2.yaml
Labels: Changelog: None

#1602 Bump main version to 0.12
  docs/conf.py
  qiskit_aer/VERSION.txt
Labels: Changelog: None, automerge

#1603 Use mainlinux2010 skip CIBW tests to release packages for GPU
  .github/workflows/deploy.yml
Labels: stable-backport-potential, automerge

#1604 Move away from `qiskit.providers.aer` in 0.11 release notes
  releasenotes/notes/0.11/fix-for-loop-no-parameter-aa5b04b1da0e956b.yaml
  releasenotes/notes/0.11/support_initialize_with_label-bc08f29928d3e3f3.yaml
Labels: documentation, stable-backport-potential, Changelog: None, automerge

#1607 Add reno branch configuration
  releasenotes/config.yaml
Labels: Changelog: None, automerge
