Repository Qiskit/qiskit-aer, pull requests merged in 2022-12, with the labels that each got.

#1672 Fix incorrect computation of excited state population
  qiskit_aer/noise/device/models.py
  releasenotes/notes/fix-temperature-a9c51c4599af3a49.yaml
Labels: stable-backport-potential, Changelog: Bugfix

#1663 Set different seed for each sampling in AerStatevector
  qiskit_aer/backends/wrappers/bindings.cc
  qiskit_aer/quantum_info/states/aer_state.py
  qiskit_aer/quantum_info/states/aer_statevector.py
  releasenotes/notes/set_seed_for_each_in_aerstatevec-ef5fcac628dec63b.yaml
  src/controllers/state_controller.hpp
  test/terra/states/test_aer_state.py
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#1671 Deprecate Python 3.7 support in Qiskit Aer
  qiskit_aer/__init__.py
  releasenotes/notes/deprecate-37-b3ec705b9f469b0b.yaml
Labels: Changelog: Deprecation, automerge

#1674 Add ECR gate support to aer simulators
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/noise/noise_model.py
  src/framework/linalg/matrix_utils/matrix_defs.hpp
  src/framework/linalg/matrix_utils/smatrix_defs.hpp
  src/framework/linalg/matrix_utils/vmatrix_defs.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/aer_simulator/test_standard_gates.py
Labels: stable-backport-potential, automerge

#1677 Specify package_data explicitly
  setup.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#1678 Fix BackendV2 support in AerSimulator.from_backend()
  qiskit_aer/backends/aer_simulator.py
  releasenotes/notes/fix-AerSimulator_from_backend_BackendV2-bccf835bc42a193d.yaml
  test/terra/backends/aer_simulator/test_from_backend.py
Labels: stable-backport-potential, Changelog: Bugfix

#1669 Release 0.11.2
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  contrib/runtime/aer_runtime.cpp
  docs/conf.py
  pyproject.toml
  qiskit_aer/VERSION.txt
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/wrappers/bindings.cc
  qiskit_aer/library/control_flow_instructions/jump.py
  qiskit_aer/library/control_flow_instructions/mark.py
  qiskit_aer/noise/device/models.py
  qiskit_aer/noise/noise_model.py
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
  qiskit_aer/quantum_info/states/aer_state.py
  qiskit_aer/quantum_info/states/aer_statevector.py
  releasenotes/notes/add-python-311-support-027047fb389116dd.yaml
  releasenotes/notes/fix-AerSimulator_from_backend_BackendV2-bccf835bc42a193d.yaml
  releasenotes/notes/fix-device-noise-models-2eca2f9c9dc25771.yaml
  releasenotes/notes/fix-temperature-a9c51c4599af3a49.yaml
  releasenotes/notes/fix-topological-control-flow-e2f1a25098004f00.yaml
  releasenotes/notes/fix-vervose-warnings-efbbbfcb4b65a2a5.yaml
  releasenotes/notes/fix_GPU_statevector-715da5ead0a59fb5.yaml
  releasenotes/notes/fix_aer_statevector_mps-c3dd40b936700ff4.yaml
  releasenotes/notes/fix_cache_blocking_AerState-ccb035bb5be6f895.yaml
  releasenotes/notes/improve-statevector-initialization-75274fdcb4106d24.yaml
  releasenotes/notes/sampler-counts-90e5aaabccdc415b.yaml
  releasenotes/notes/set_seed_for_each_in_aerstatevec-ef5fcac628dec63b.yaml
  requirements-dev.txt
  setup.py
  src/controllers/aer_controller.hpp
  src/controllers/state_controller.hpp
  src/framework/linalg/matrix_utils/matrix_defs.hpp
  src/framework/linalg/matrix_utils/smatrix_defs.hpp
  src/framework/linalg/matrix_utils/vmatrix_defs.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/transpile/cacheblocking.hpp
  test/terra/backends/aer_simulator/test_control_flow.py
  test/terra/backends/aer_simulator/test_from_backend.py
  test/terra/backends/aer_simulator/test_standard_gates.py
  test/terra/noise/test_device_models.py
  test/terra/noise/test_noise_model.py
  test/terra/primitives/test_sampler.py
  test/terra/states/test_aer_state.py
  test/terra/states/test_aer_statevector.py
  tools/install_openblas_i686.sh
  tox.ini
Labels: Changelog: None
