Repository Qiskit/qiskit-aer, pull requests merged in 2022-05, with the labels that each got.

#1512 Generate seeds deterministically based on seed of the first circuit in multi-circuit simulation if seed_simulator is not set
  releasenotes/notes/make_random_seed_reproducible-a7abdfc09ec67bd8.yaml
  src/framework/qobj.hpp
  test/terra/backends/test_parameterized_qobj.py
Labels: stable-backport-potential

#1518 Add mergify configuration
  .mergify.yml
Labels: Changelog: None

#1513 Reduce dependency to ClassicalRegister from AER::QV::QubitVector
  src/simulators/state_chunk.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
Labels: Changelog: None, automerge

#1521 Fix import path for deprecated Pauli
  qiskit/providers/aer/noise/errors/standard_errors.py
Labels: stable-backport-potential
