Repository Qiskit/qiskit-aer, pull requests merged in 2023-06, with the labels that each got.

#1827 Fixing some typos
  CONTRIBUTING.md
  README.md
  qiskit_aer/quantum_info/states/aer_densitymatrix.py
  qiskit_aer/quantum_info/states/aer_statevector.py
Labels: documentation, stable-backport-potential, automerge

#1830 Use transpile and run instead of execute in docstring
  qiskit_aer/noise/__init__.py
Labels: documentation, stable-backport-potential, automerge

#1833 Fix typos in aer_simulator, qasm_simulator docs
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/qasm_simulator.py
Labels: automerge

#1823 Warn if approximation=False and shots=None in Estimator
  qiskit_aer/primitives/estimator.py
  test/terra/primitives/test_estimator.py
Labels: stable-backport-potential, automerge

#1839 Fix the grouping index bug in Estimator
  qiskit_aer/primitives/estimator.py
  releasenotes/notes/primitives-grouping-index-bug-56f69afbdc3e86a0.yaml
  test/terra/primitives/test_estimator.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#1772 Do not use circuit metadata to internally manage simulation results
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/wrappers/aer_circuit_binding.hpp
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/do_not_modify_metadata-60bb4b88707bd021.yaml
  src/controllers/aer_controller.hpp
  src/controllers/controller_execute.hpp
  src/framework/qobj.hpp
  src/framework/results/experiment_result.hpp
  src/framework/results/pybind_result.hpp
  test/terra/backends/aer_simulator/test_circuit.py
Labels: stable-backport-potential

#1842 Fix MPI build break
  src/controllers/aer_controller.hpp
Labels: stable-backport-potential, Changelog: None

#1840 Batch QuantumCircuit with multiple parameter_binds
  qiskit_aer/primitives/estimator.py
  releasenotes/notes/estimator-performance-da83a59b9fd69086.yaml
Labels: Changelog: None

#1845 Remove `AerCircuit` from result of `backend.run()`
  qiskit_aer/backends/aerbackend.py
  releasenotes/notes/remove_aer_circuit_from_metadata-e4fe09029c1a3a3c.yaml
  test/terra/backends/aer_simulator/test_circuit.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge
