Repository Qiskit/qiskit-aer, pull requests merged in 2023-10, with the labels that each got.

#1951 Fix matplotlib version
  .github/workflows/docs.yml
  releasenotes/notes/fix_matplotlib_dependency-5b8ba26da6a98e3a.yaml
Labels: automerge

#1945 Update usage of ``QuantumCircuit.id``
  qiskit_aer/backends/backend_utils.py
  test/terra/backends/simulator_test_case.py
  test/terra/decorators.py
  test/terra/noise/test_noise_model.py
  test/terra/noise/test_quantum_error.py
  test/terra/reference/ref_algorithms.py
  test/terra/reference/ref_kraus_noise.py
  test/terra/reference/ref_measure.py
  test/terra/reference/ref_pauli_noise.py
  test/terra/reference/ref_reset_noise.py
  test/terra/reference/ref_save_expval.py
  tools/generate_qobj.py
  tools/verify_wheels.py
Labels: Changelog: Deprecation, automerge

#1901 Implementing runtime parameter binding
  CMakeLists.txt
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/add_executor-ba4870f86ed5d8ec.yaml
  releasenotes/notes/runtime_parameter_binding-d2c57255f02729a1.yaml
  src/controllers/aer_controller.hpp
  src/controllers/controller_execute.hpp
  src/framework/circuit.hpp
  src/framework/config.hpp
  src/framework/operations.hpp
  src/framework/results/data/metadata.hpp
  src/framework/results/data/subtypes/data_map.hpp
  src/noise/noise_model.hpp
  src/simulators/batch_shots_executor.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/density_matrix/densitymatrix_executor.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/multi_state_executor.hpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/shot_branching.hpp
  src/simulators/state.hpp
  src/simulators/statevector/chunk/chunk.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/chunk_manager.hpp
  src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
  src/simulators/statevector/chunk/cuda_kernels.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/host_chunk_container.hpp
  src/simulators/statevector/chunk/thrust_kernels.hpp
  src/simulators/statevector/indexes.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_executor.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/tensor_network/tensor_net_executor.hpp
  src/simulators/tensor_network/tensor_net_state.hpp
  src/simulators/unitary/unitary_executor.hpp
  src/simulators/unitary/unitary_state.hpp
  src/transpile/batch_converter.hpp
  src/transpile/fusion.hpp
  src/transpile/parameter2matrix.hpp
  test/terra/backends/test_runtime_parameterization.py
Labels: enhancement, Changelog: New Feature

#1942 Implementation and test of QuantumError.from_dict.
  qiskit_aer/noise/errors/quantum_error.py
  releasenotes/notes/quantum_error_from_dict-8188a864109edd67.yaml
  test/terra/noise/test_quantum_error.py
Labels: Changelog: New Feature

#1868 enable `c_if` for reset and raise exception if instruction does not support `c_if`
  qiskit_aer/backends/aer_compiler.py
  releasenotes/notes/support_c_if_reset-1f0b8e84948fb3fc.yaml
  src/framework/circuit.hpp
  src/framework/operations.hpp
  src/transpile/fusion.hpp
  test/terra/backends/aer_simulator/test_conditional.py
  test/terra/reference/ref_conditionals.py
Labels: Changelog: New Feature

#1869 Add test case to serialize result of simulation
  test/terra/backends/aer_simulator/test_executors.py
Labels: Changelog: None, automerge

#1915 Support `Expr` that Terra 0.24 newly introduced
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/wrappers/aer_circuit_binding.hpp
  qiskit_aer/library/control_flow_instructions/jump.py
  releasenotes/notes/support_classical_expr-dd621e5c0fd23a15.yaml
  src/framework/circuit.hpp
  src/framework/creg.hpp
  src/framework/operations.hpp
  src/noise/noise_model.hpp
  src/simulators/batch_shots_executor.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  test/terra/backends/aer_simulator/test_control_flow.py
  test/terra/expression/test_classical_expressions.py
Labels: Changelog: New Feature

#1950 Add test for unreleased Qiskit
  .github/workflows/tests.yml
  .github/workflows/unit-tests-latest-qiskit.yml
  qiskit_aer/backends/aer_compiler.py
  test/benchmark/simulator_benchmark.py
  test/terra/backends/aer_simulator/test_fusion.py
  test/terra/backends/test_parameterized_qobj.py
  test/terra/backends/test_runtime_parameterization.py
  test/terra/primitives/test_estimator.py
Labels: Changelog: None, automerge

#1962 support transpilation of switch_case
  qiskit_aer/backends/backend_utils.py
  releasenotes/notes/support_switch_transpilation-67e16241b94faa86.yaml
  test/terra/backends/aer_simulator/test_control_flow.py
Labels: Changelog: Bugfix

#1963 Deprecate approximation option in Estimator
  qiskit_aer/primitives/estimator.py
  test/terra/primitives/test_estimator.py
Labels: Changelog: Deprecation

#1954 [rebranding] Qiskit Aer is now Aer
  CONTRIBUTING.md
  README.md
  qiskit_aer/__init__.py
  qiskit_aer/aererror.py
  qiskit_aer/aerprovider.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/statevector_simulator.py
  qiskit_aer/backends/unitary_simulator.py
  qiskit_aer/jobs/aerjob.py
  qiskit_aer/jobs/aerjobset.py
  qiskit_aer/noise/errors/quantum_error.py
  qiskit_aer/noise/errors/readout_error.py
  qiskit_aer/noise/errors/standard_errors.py
  qiskit_aer/noise/noise_model.py
  qiskit_aer/noise/noiseerror.py
  setup.py
Labels: automerge

#1965 Add skip Python 3.12 for GPU build
  .github/workflows/deploy.yml
Labels: Changelog: None, automerge
