Repository Qiskit/qiskit-aer, pull requests merged in 2023-05, with the labels that each got.

#1786 Remove REQUIRED to find PythonLibs in FindPybind11
  cmake/FindPybind11.cmake
Labels: Changelog: None, automerge

#1801 Fix library path to cuQuantum and cuTENSOR
  CMakeLists.txt
  releasenotes/notes/fix_cuQuantum_libpath-90d24880cd9a9ea8.yaml
Labels: stable-backport-potential, automerge

#1812 Fix cuQuantum static linking
  CMakeLists.txt
  releasenotes/notes/fix_cuQuantum_static-ad132d742a64a3d5.yaml
Labels: stable-backport-potential, automerge

#1799 Updated docstrings of depolarizing_error function in standard_errors.py
  qiskit_aer/noise/errors/standard_errors.py
Labels: stable-backport-potential, automerge

#1770 Add implicit cast of argument types
  qiskit_aer/backends/aer_compiler.py
  releasenotes/notes/implicit_cast_for_arguments-a3c671db2fff6f17.yaml
  test/terra/backends/aer_simulator/test_circuit.py
Labels: stable-backport-potential

#1818 Fix handling of None in noise model construction from BackendV2
  qiskit_aer/noise/device/models.py
  qiskit_aer/noise/noise_model.py
  releasenotes/notes/fix-none-handling-in-noise-model-34fcc9a3e3cbdf6f.yaml
  test/terra/noise/test_device_models.py
  test/terra/noise/test_noise_model.py
Labels: stable-backport-potential, Changelog: Bugfix

#1780 Add Getting Started page
  docs/apidocs/aer.rst
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/howtos/index.rst
  docs/howtos/parallel.rst
  docs/howtos/running_gpu.rst
  docs/index.rst
  requirements-dev.txt
Labels: stable-backport-potential

#1791 Avoid kernel crash from blas call errors
  releasenotes/notes/avoid_kernel_crash_in_mac_from_blas_error-bd5b836a23f2e3ee.yaml
  src/noise/noise_model.hpp
Labels: stable-backport-potential, automerge

#1814 Support parameterized global phase
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/support_param_for_global_phase-704a97129e7bdbaa.yaml
  src/controllers/controller_execute.hpp
  src/framework/config.hpp
  src/framework/qobj.hpp
  test/terra/backends/test_parameterized_qobj.py
Labels: stable-backport-potential

#1817 Check parameter_binds arguments for parameterized circuits
  qiskit_aer/backends/aerbackend.py
  releasenotes/notes/check_parameter_binds_exist-9d52c665d5f94dde.yaml
  test/terra/backends/test_parameterized_qobj.py
Labels: stable-backport-potential, automerge

#1825 Set the number of qubits with the coupling map
  qiskit_aer/backends/aer_simulator.py
  releasenotes/notes/fix-number-qubits-a417ca6afa64264f.yaml
  test/terra/backends/aer_simulator/test_options.py
Labels: stable-backport-potential, automerge
