Repository Qiskit/qiskit-aer, pull requests merged in 2023-08, with the labels that each got.

#1887 Fix link to Qiskit's bib-file
  README.md
Labels: Changelog: None

#1766 Adding circuit executor classes and shot-branching
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/add_executor-a03f2d23cf6f4ca9.yaml
  src/controllers/aer_controller.hpp
  src/controllers/state_controller.hpp
  src/framework/config.hpp
  src/framework/operations.hpp
  src/framework/results/experiment_result.hpp
  src/framework/utils.hpp
  src/noise/noise_model.hpp
  src/simulators/batch_shots_executor.hpp
  src/simulators/chunk_utils.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/density_matrix/densitymatrix.hpp
  src/simulators/density_matrix/densitymatrix_executor.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/extended_stabilizer/ch_runner.hpp
  src/simulators/multi_state_executor.hpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/shot_branching.hpp
  src/simulators/simulators.hpp
  src/simulators/stabilizer/clifford.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/chunk/chunk.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/chunk_manager.hpp
  src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/host_chunk_container.hpp
  src/simulators/statevector/chunk/thrust_kernels.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/statevector/statevector_executor.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator.hpp
  src/simulators/superoperator/superoperator_thrust.hpp
  src/simulators/tensor_network/tensor_net_contractor.hpp
  src/simulators/tensor_network/tensor_net_contractor_cuTensorNet.hpp
  src/simulators/tensor_network/tensor_net_executor.hpp
  src/simulators/tensor_network/tensor_net_state.hpp
  src/simulators/unitary/unitary_executor.hpp
  src/simulators/unitary/unitary_state.hpp
  src/simulators/unitary/unitarymatrix.hpp
  src/simulators/unitary/unitarymatrix_thrust.hpp
  test/terra/backends/aer_simulator/test_conditional.py
  test/terra/backends/aer_simulator/test_measure.py
  test/terra/backends/aer_simulator/test_shot_branching.py
  test/terra/backends/simulator_test_case.py
  test/terra/common.py
  tox.ini
Labels: enhancement, Changelog: New Feature

#1892 Implemented ecr for stabilizer simulator.
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/qasm_simulator.py
  releasenotes/notes/enhancement_ecr_for_stabilizer_simulator-00110a1b39d35054.yaml
  src/simulators/stabilizer/stabilizer_state.hpp
  test/terra/backends/aer_simulator/test_cliffords.py
  test/terra/reference/ref_2q_clifford.py
Labels: enhancement

#1891 remove deploy documentation to /documentation/aer
  tools/deploy_documentation.sh
Labels: Changelog: None, automerge

#1898 correct bit ordering in measure of state_controller
  releasenotes/notes/correct_measure_in_state_controller-a92692fd7083c476.yaml
  src/controllers/state_controller.hpp
Labels: stable-backport-potential, Changelog: Bugfix

#1903 Change the the existing CUDA implementation to a generic GPU implementation.
  CMakeLists.txt
  src/controllers/aer_controller.hpp
  src/controllers/state_controller.hpp
  src/misc/gpu_static_properties.hpp
  src/misc/wrap_thrust.hpp
  src/simulators/batch_shots_executor.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/density_matrix/densitymatrix_thrust.hpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/statevector/chunk/chunk.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/chunk_manager.hpp
  src/simulators/statevector/chunk/cuda_kernels.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/thrust_kernels.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/unitary/unitarymatrix_thrust.hpp
Labels: enhancement, Changelog: New Feature

#1904 Fix errors coming from deprecations in recent NumPy versions.
  qiskit_aer/quantum_info/states/aer_densitymatrix.py
  qiskit_aer/quantum_info/states/aer_statevector.py
  test/terra/backends/aer_simulator/test_save_matrix_product_state.py
Labels: stable-backport-potential, Changelog: Bugfix

#1912 Fix noise model construction for a backend with no T2 value for a qubit
  qiskit_aer/noise/device/models.py
  releasenotes/notes/fix-none-t2-handling-in-noise-model-5b712adf3569eccd.yaml
  test/terra/noise/test_device_models.py
Labels: stable-backport-potential, Changelog: Bugfix

#1909 Make vector allocation aligned to 64-bytes
  releasenotes/notes/fix-aer-vector-alignment-aace6e14342c002e.yaml
  src/framework/linalg/vector.hpp
Labels: stable-backport-potential, Changelog: Bugfix
