Repository Qiskit/qiskit-aer, pull requests merged in 2023-01, with the labels that each got.

#1680 Fix `Sampler` with multiple classical registers
  qiskit_aer/primitives/sampler.py
  releasenotes/notes/fix-split-cregs-5b5494a92c4903e7.yaml
  test/terra/primitives/test_sampler.py
Labels: Changelog: Bugfix, automerge

#1693 Remove setup_requires and forced pip installs in setup.py
  .github/workflows/tests.yml
  CONTRIBUTING.md
  releasenotes/notes/remove-setup_requires-751a406e2782885e.yaml
  setup.py
  tox.ini
Labels: build system, Changelog: API Change

#1691 Replace IBMQ with IBM Quantum in Aer documention.
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/qasm_simulator.py
Labels: documentation, automerge

#1690 Remove deprecated module import
  test/terra/backends/aer_simulator/test_truncate.py
Labels: Changelog: None, automerge

#1635 Remove qobj argument, deprecated in 0.8.0
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/pulse_simulator.py
  releasenotes/notes/remove-qobj-684e68e99b212973.yaml
Labels: Changelog: Removal, automerge

#1474 Add NoiseModel.from_backend_properties
  qiskit_aer/noise/noise_model.py
  releasenotes/notes/add-NoiseModel-from_backendproperties-1a3d6d976133a661.yaml
  test/terra/noise/test_noise_model.py
Labels: Changelog: New Feature, automerge

#1673 Add `__init__.py` to run tests for terra.states
  .github/workflows/tests.yml
  requirements-dev.txt
  test/terra/states/__init__.py
  test/terra/states/test_aer_statevector.py
Labels: automerge

#1685 Guarantee ndarray contiguity
  qiskit_aer/quantum_info/states/aer_statevector.py
  test/terra/states/test_aer_statevector.py
Labels: automerge

#1710 Fix test_aer_statevector
  docs/conf.py
  test/terra/states/test_aer_statevector.py
Labels: automerge

#1705 Add release note for #1685
  releasenotes/notes/fix-ndarray-contiguity-e903d0fda4744100.yaml
Labels: automerge

#1703 Add a work around for Aer installation issue in Neko
  .github/workflows/neko.yml
Labels: automerge
