Repository Qiskit/qiskit-aer, pull requests merged in 2023-03, with the labels that each got.

#1717 Simulate `QuantumCircuit` without QObj
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/pulse_simulator.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/statevector_simulator.py
  qiskit_aer/backends/unitary_simulator.py
  qiskit_aer/backends/wrappers/aer_circuit_binding.hpp
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  qiskit_aer/backends/wrappers/aer_state_binding.hpp
  qiskit_aer/backends/wrappers/bindings.cc
  qiskit_aer/jobs/aerjob.py
  qiskit_aer/quantum_info/states/aer_state.py
  releasenotes/notes/own_assembler-0c76e67a054bd12c.yaml
  src/controllers/aer_controller.hpp
  src/controllers/controller_execute.hpp
  src/framework/circuit.hpp
  src/framework/config.hpp
  src/framework/linalg/vector.hpp
  src/framework/operations.hpp
  src/framework/pybind_json.hpp
  src/framework/results/experiment_result.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/state.hpp
  src/simulators/state_chunk.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/superoperator/superoperator_state.hpp
  src/simulators/tensor_network/tensor_net_state.hpp
  src/simulators/unitary/unitary_state.hpp
  src/transpile/cacheblocking.hpp
  src/transpile/circuitopt.hpp
  src/transpile/fusion.hpp
  test/terra/backends/aer_simulator/test_auto_method.py
  test/terra/backends/aer_simulator/test_circuit.py
  test/terra/backends/aer_simulator/test_conditional.py
  test/terra/backends/simulator_test_case.py
Labels: Changelog: New Feature

#1733 Use qiskit_sphinx_theme for API doc
  docs/_static/style.css
  docs/conf.py
  docs/index.rst
  requirements-dev.txt
Labels: documentation, Changelog: None, automerge

#1739 Prepare 0.12.0 release
  releasenotes/notes/0.12/add-NoiseModel-from_backendproperties-1a3d6d976133a661.yaml
  releasenotes/notes/0.12/add-aer-density-matrix-e2439120b24c91c9.yaml
  releasenotes/notes/0.12/add-grouping-fcc4fad69ccdac26.yaml
  releasenotes/notes/0.12/add_initialize_density_matrix-a72b1a614b09726e.yaml
  releasenotes/notes/0.12/delete-args-and-methods-in-primitives-8013546db867e849.yaml
  releasenotes/notes/0.12/deprecate-37-b3ec705b9f469b0b.yaml
  releasenotes/notes/0.12/deprecate-pulse-simulator-27cde3ece112c346.yaml
  releasenotes/notes/0.12/fix-ndarray-contiguity-e903d0fda4744100.yaml
  releasenotes/notes/0.12/fix-split-cregs-5b5494a92c4903e7.yaml
  releasenotes/notes/0.12/fix_batch_execution-da4d88dbee26731b.yaml
  releasenotes/notes/0.12/fix_tensor_network_not_installed-a23b8ef65e6e643e.yaml
  releasenotes/notes/0.12/mps_fix_apply_measure-84c29a728ae0e717.yaml
  releasenotes/notes/0.12/optimized_stabilizer-f696742e7f881d0d.yaml
  releasenotes/notes/0.12/own_assembler-0c76e67a054bd12c.yaml
  releasenotes/notes/0.12/prepare-0.12-0da477fc0492ca5d.yaml
  releasenotes/notes/0.12/remove-deprecated-noise-functions-52128d161d3327e9.yaml
  releasenotes/notes/0.12/remove-qobj-684e68e99b212973.yaml
  releasenotes/notes/0.12/remove-setup_requires-751a406e2782885e.yaml
  releasenotes/notes/0.12/support_break_and_continue_gates-bf30316fcacd4b6b.yaml
  releasenotes/notes/0.12/support_kraus-ec31e636c6793b8c.yaml
  releasenotes/notes/0.12/tensor_network_gpu-e8eb3e40be3c35f7.yaml
  releasenotes/notes/0.12/use_conan_1.x-f12570e2cfc8bb26.yaml
  releasenotes/notes/0.12/use_specified_bla_vendor-ca0322e993378048.yaml
  releasenotes/notes/add-NoiseModel-from_backendproperties-1a3d6d976133a661.yaml
  releasenotes/notes/add-grouping-fcc4fad69ccdac26.yaml
  releasenotes/notes/add-python-311-support-027047fb389116dd.yaml
  releasenotes/notes/cmake_cuda_arch-817eb0b7232bd291.yaml
  releasenotes/notes/fix-AerSimulator_from_backend_BackendV2-bccf835bc42a193d.yaml
  releasenotes/notes/fix-device-noise-models-2eca2f9c9dc25771.yaml
  releasenotes/notes/fix-local-noise-pass-83815d5a80f9a0e9.yaml
  releasenotes/notes/fix-ndarray-contiguity-e903d0fda4744100.yaml
  releasenotes/notes/fix-split-cregs-5b5494a92c4903e7.yaml
  releasenotes/notes/fix-temperature-a9c51c4599af3a49.yaml
  releasenotes/notes/fix-topological-control-flow-e2f1a25098004f00.yaml
  releasenotes/notes/fix-vervose-warnings-efbbbfcb4b65a2a5.yaml
  releasenotes/notes/fix_GPU_statevector-715da5ead0a59fb5.yaml
  releasenotes/notes/fix_aer_statevector_mps-c3dd40b936700ff4.yaml
  releasenotes/notes/fix_bug_in_tail_while-6a9201d1ad6ba6e8.yaml
  releasenotes/notes/fix_cache_blocking_AerState-ccb035bb5be6f895.yaml
  releasenotes/notes/improve-statevector-initialization-75274fdcb4106d24.yaml
  releasenotes/notes/mps_fix_apply_measure-84c29a728ae0e717.yaml
  releasenotes/notes/optimized_stabilizer-f696742e7f881d0d.yaml
  releasenotes/notes/own_assembler-0c76e67a054bd12c.yaml
  releasenotes/notes/remove-qobj-684e68e99b212973.yaml
  releasenotes/notes/sampler-cache-78f916cedb0c5421.yaml
  releasenotes/notes/sampler-counts-90e5aaabccdc415b.yaml
  releasenotes/notes/set_seed_for_each_in_aerstatevec-ef5fcac628dec63b.yaml
  releasenotes/notes/support_terra_primitive_022-8852b784608bcdcb.yaml
  releasenotes/notes/tensor_network_gpu-e8eb3e40be3c35f7.yaml
  releasenotes/notes/use_conan_1.x-f12570e2cfc8bb26.yaml
  releasenotes/notes/use_specified_bla_vendor-ca0322e993378048.yaml
Labels: Changelog: None, automerge

#1740 Bump version string post release
  docs/conf.py
  qiskit_aer/VERSION.txt
Labels: Changelog: None, automerge

#1741 Remove redundant wheel dep from pyproject.toml
  pyproject.toml
Labels: Changelog: None, automerge

#1745 Add git blame ignore file
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: Changelog: None, automerge

#1748 deploy documentation in qiskit.org/ecosystem
  tools/deploy_documentation.sh
Labels: stable-backport-potential, Changelog: None, automerge

#1750 Remove a release note in an invalid location
  releasenotes/add-aer-densitymatrix-959c261c954fa60e.yaml
Labels: stable-backport-potential, automerge

#1749 Fix how to reference to config.cuStateVec_enable
  releasenotes/notes/fix-cuStateVec_enable-0936f2269466e3be.yaml
  src/simulators/state_chunk.hpp
Labels: stable-backport-potential, automerge

#1752 use `omp_set_max_active_levels` instead of `omp_set_nested`
  releasenotes/notes/use_omp_set_max_active_levels-7e6c1d301c4434a6.yaml
  src/controllers/aer_controller.hpp
Labels: stable-backport-potential

#1761 Ensure QuantumCircuit.metadata is always a dict
  qiskit_aer/backends/aerbackend.py
Labels: stable-backport-potential, Changelog: None, automerge

#1767 Fix #1764 (variance type in Estimator)
  qiskit_aer/primitives/estimator.py
  releasenotes/notes/estimator-variance-type-2b04ff7bcd305920.yaml
  test/terra/primitives/test_estimator.py
Labels: stable-backport-potential
