Repository Qiskit/qiskit-aer, pull requests merged in 2023-09, with the labels that each got.

#1907 For https://github.com/Qiskit/qiskit-aer/issues/1905 and https://gith…
  cmake/conan.cmake
  releasenotes/notes/latest-vc++-compilation-fixes-555601315e7e821b.yaml
  src/transpile/cacheblocking.hpp
Labels: Changelog: Bugfix

#1914 Enable ROCm target based on existing CUDA/Thrust implementation.
  CMakeLists.txt
  CONTRIBUTING.md
  cmake/conan_utils.cmake
  qiskit_aer/backends/wrappers/CMakeLists.txt
  releasenotes/notes/add-rocm-support-db991e3c2f2ca455.yaml
  setup.py
  src/misc/gpu_static_properties.hpp
  src/misc/hipify.hpp
  src/misc/wrap_thrust.hpp
  src/simulators/extended_stabilizer/gates.hpp
  src/simulators/statevector/chunk/chunk_container.hpp
  src/simulators/statevector/chunk/device_chunk_container.hpp
  src/simulators/statevector/chunk/host_chunk_container.hpp
  src/simulators/statevector/chunk/thrust_kernels.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
Labels: enhancement, Changelog: New Feature

#1926 Fix for https://github.com/Qiskit/qiskit-aer/issues/1925 (Aer runtime…
  contrib/runtime/aer_runtime.cpp
  releasenotes/notes/aer-runtime-api-exposed-wrong-sx-op-dadae6cf0787e169.yaml
  src/controllers/state_controller.hpp
Labels: stable-backport-potential, Changelog: Bugfix

#1895 Fix measure in stabilizer method
  releasenotes/notes/fix_stabilizer_measure-49f9b4261dfaa4d3.yaml
  src/simulators/stabilizer/clifford.hpp
  test/terra/backends/aer_simulator/test_measure.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#1922 Fix for https://github.com/Qiskit/qiskit-aer/issues/1918
  releasenotes/notes/fix-compiling-issue-in-release-with-vc++-47500a37841cfaa8.yaml
  src/simulators/statevector/qv_avx2.cpp
Labels: stable-backport-potential, Changelog: Bugfix

#1933 Fix required_memory_mb for MPS and extended stabilizer
  releasenotes/notes/fix_mps_extstabilizer_required_memory-f4fb0aebfeeb68e2.yaml
  src/controllers/aer_controller.hpp
  src/simulators/batch_shots_executor.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/density_matrix/densitymatrix_executor.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_size_estimator.hpp
  src/simulators/multi_state_executor.hpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/statevector/statevector_executor.hpp
Labels: stable-backport-potential, Changelog: Bugfix

#1938 Add rotation gates to stabilizer
  qiskit_aer/backends/backend_utils.py
  releasenotes/notes/stabilizer_rotation-8ce2effd9578ee0a.yaml
  src/simulators/circuit_executor.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/state.hpp
  test/terra/backends/aer_simulator/test_rotation.py
  test/terra/primitives/test_estimator.py
  test/terra/primitives/test_sampler.py
  test/terra/reference/ref_rotation.py
Labels: enhancement

#1939 Fix incorrect excited state population when building noise model from BackendV2
  qiskit_aer/noise/device/models.py
  releasenotes/notes/fix-excitation-population-6af281a61f659dda.yaml
  test/terra/noise/test_device_models.py
  tox.ini
Labels: Changelog: Bugfix

#1935 Improve performance of sampler experiment
  qiskit_aer/primitives/sampler.py
  releasenotes/notes/sampler-performance-81e1649ec4657aad.yaml
Labels: performance

#1936 Fix the order bug in Estimator
  qiskit_aer/primitives/estimator.py
  releasenotes/notes/estimator-order-bug-a341d82075f47046.yaml
  test/terra/primitives/test_estimator.py
Labels: stable-backport-potential, Changelog: Bugfix

#1949 Fix nested parallel performance
  releasenotes/notes/fix_omp_nested_performance-a3d55f3e85366a5b.yaml
  src/controllers/aer_controller.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/unitary/unitarymatrix.hpp
  src/transpile/fusion.hpp
Labels: Changelog: Bugfix, automerge
