Repository Qiskit/qiskit-aer, pull requests merged in 2023-07, with the labels that each got.

#1860 Fix a bug in `aer_apply_measure` in libaer and enable libaer build in Mac
  CMakeLists.txt
  contrib/runtime/aer_runtime.cpp
Labels: Changelog: None, automerge

#1846 Support save_statevector for QuantumCircuit from QASM3 string
  qiskit_aer/library/default_qubits.py
  releasenotes/notes/save_statevector_for_qasm3_circ-642ade99af3ff0d2.yaml
  requirements-dev.txt
  test/terra/backends/aer_simulator/test_save_statevector.py
Labels: stable-backport-potential, automerge

#1867 bump up python version from 3.7 to 3.8 to run cibuildwheel
  .github/workflows/deploy.yml
Labels: stable-backport-potential, Changelog: None, automerge

#1871 set numpy version constraint only in dev
  constraints.txt
  setup.py
Labels: stable-backport-potential, Changelog: None

#1819 Remove Python 3.7 from Github actions
  .github/workflows/build.yml
  .github/workflows/tests.yml
  pyproject.toml
Labels: Changelog: None

#1877 Fix dynamic link in GPU binary distribution
  .github/workflows/deploy.yml
  CMakeLists.txt
  qiskit_aer/backends/wrappers/CMakeLists.txt
  releasenotes/notes/fix_gpu_binary-1b5b162dff76060d.yaml
Labels: automerge

#1880 Fix OpenMP nested parallel
  releasenotes/notes/fix_omp_nested-a554de2e7fd2a2d6.yaml
  src/controllers/aer_controller.hpp
Labels: stable-backport-potential, automerge

#1876 Support u3 gate application in Aer runtime API
  contrib/runtime/aer_runtime.cpp
  contrib/runtime/aer_runtime_api.h
  releasenotes/notes/support_u3_runtime_api-42f013f111c319ff.yaml
Labels: Changelog: New Feature, automerge

#1881 Fix required_memory_mb
  releasenotes/notes/fix_required_memory_mb-7aeafa0fe553b85a.yaml
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/statevector/qubitvector.hpp
  src/simulators/statevector/qubitvector_thrust.hpp
  src/simulators/unitary/unitary_state.hpp
Labels: stable-backport-potential, automerge
