Repository Qiskit/qiskit-aer, pull requests merged in 2024-02, with the labels that each got.

#2045 Remove muparserx from cmake configuration
  CMakeLists.txt
  cmake/conan_utils.cmake
  cmake/dependency_utils.cmake
Labels: stable-backport-potential

#2041 Remove importing qiskit.execute
  test/terra/decorators.py
  tools/verify_wheels.py
Labels: stable-backport-potential, Changelog: Deprecation

#2048 Add private primitive attributes removed by qiskit
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
  test/terra/primitives/test_estimator.py
Labels: automerge

#2052 Release0.13.3
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests-latest-qiskit.yml
  README.md
  docs/conf.py
  qiskit_aer/VERSION.txt
  qiskit_aer/primitives/estimator.py
  qiskit_aer/primitives/sampler.py
  releasenotes/notes/0.13/release0.13.1-a07688e4eb04b9d6.yaml
  releasenotes/notes/fix_for_daily_tests-3fa9df70fb3e53ee.yaml
  releasenotes/notes/fix_test_for_Qiskit0.45.2-e0544949be8e77fb.yaml
  releasenotes/notes/release0.13.3-b144015572a25737.yaml
  test/benchmark/vqe_application.py
  test/terra/backends/aer_simulator/test_conditional.py
  test/terra/backends/aer_simulator/test_from_backend.py
  test/terra/backends/aer_simulator/test_options.py
  test/terra/backends/aer_simulator/test_truncate.py
  test/terra/decorators.py
  test/terra/noise/test_device_models.py
  test/terra/noise/test_noise_model.py
  test/terra/primitives/test_estimator.py
  test/terra/reference/ref_diagonal_gate.py
  test/terra/reference/ref_multiplexer.py
  test/terra/states/test_aer_state.py
  test/terra/states/test_aer_statevector.py
  tools/verify_wheels.py
Labels: automerge

#2054 Only run sdist build after wheel builds are uploaded
  .github/workflows/deploy.yml
Labels: automerge

#2059 Fix required memory estimation for MPS
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/fix_mps_required_memory_estimation-75a9bb739701046c.yaml
  src/controllers/aer_controller.hpp
  src/framework/config.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_size_estimator.hpp
Labels: stable-backport-potential, Changelog: Bugfix

#2064 Fix qiskit-aer/library/save-instructions/save_data.py
  .github/workflows/build.yml
  pyproject.toml
  qiskit_aer/library/save_instructions/save_data.py
  tox.ini
Labels: stable-backport-potential, Changelog: None
