Repository Qiskit/qiskit-aer, pull requests merged in 2024-08, with the labels that each got.

#2201 Fixes for Qiskit 1.2
  .github/workflows/unit-tests-latest-qiskit.yml
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/backendconfiguration.py
  qiskit_aer/backends/backendproperties.py
  qiskit_aer/backends/name_mapping.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/statevector_simulator.py
  qiskit_aer/backends/unitary_simulator.py
  qiskit_aer/noise/errors/quantum_error.py
  qiskit_aer/noise/noise_model.py
  releasenotes/notes/fix_for_qiskit1.2-4924037bafe82ecc.yaml
  src/framework/pybind_json.hpp
  test/terra/backends/aer_simulator/test_circuit.py
  test/terra/backends/aer_simulator/test_executors.py
  test/terra/backends/aer_simulator/test_measure.py
  test/terra/backends/aer_simulator/test_options.py
  test/terra/backends/aer_simulator/test_truncate.py
  test/terra/backends/aer_simulator/test_unitary_gate.py
  test/terra/backends/aer_simulator/test_wrapper_statevector_simulator.py
  test/terra/backends/aer_simulator/test_wrapper_unitary_simulator.py
  test/terra/backends/simulator_test_case.py
  test/terra/backends/test_parameterized_qobj.py
  test/terra/backends/test_runtime_parameterization.py
  test/terra/extensions/test_wrappers.py
  test/terra/noise/test_device_models.py
  test/terra/noise/test_noise_model.py
  test/terra/primitives/test_sampler_v2.py
Labels: stable-backport-potential, Changelog: Deprecation, Changelog: Bugfix

#2187 Remove standalone and qobj
  .github/workflows/build.yml
  .gitignore
  CMakeLists.txt
  CONTRIBUTING.md
  contrib/standalone/qasm_simulator.cpp
  contrib/standalone/version.hpp.in
  docs/howtos/parallel.rst
  qiskit_aer/__init__.py
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/statevector_simulator.py
  qiskit_aer/backends/unitary_simulator.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  qiskit_aer/jobs/__init__.py
  qiskit_aer/jobs/aerjob.py
  qiskit_aer/jobs/aerjobset.py
  qiskit_aer/jobs/utils.py
  qiskit_aer/library/save_instructions/save_data.py
  qiskit_aer/noise/noise_model.py
  releasenotes/notes/0.9/custom-executor-3d0048b4dd4fa722.yaml
  releasenotes/notes/remove-standalone-qobj-0fc0f7ca479634f4.yaml
  setup.py
  src/controllers/aer_controller.hpp
  src/controllers/controller_execute.hpp
  src/controllers/state_controller.hpp
  src/framework/operations.hpp
  src/framework/qobj.hpp
  test/CMakeLists.txt
  test/data/qobj_snapshot_expval_matrix.json
  test/data/qobj_snapshot_expval_pauli.json
  test/data/qobj_snapshot_probs.json
  test/data/qobj_snapshot_statevector.json
  test/src/test_linalg.cpp
  test/src/test_snapshot.cpp
  test/src/test_snapshot_bdd.cpp
  test/src/utils.hpp
  test/terra/backends/aer_simulator/test_job_splitting.py
  test/terra/backends/test_parameterized_circuit.py
  test/terra/backends/test_runtime_parameterization.py
  tools/generate_qobj.py
  tools/verify_wheels.py
Labels: Changelog: Deprecation

#2208 run `pip check` again in macos CI
  .github/workflows/tests.yml
Labels: stable-backport-potential

#2209 Fix parameter array initialization for runtime parameter binding
  releasenotes/notes/fix_parameter_bind_rpb-23d8bfbb8ee8d0f4.yaml
  src/controllers/controller_execute.hpp
  src/noise/noise_model.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/parallel_state_executor.hpp
  test/terra/backends/test_runtime_parameterization.py
Labels: Changelog: Bugfix
