Repository Qiskit/qiskit-aer, pull requests merged in 2024-03, with the labels that each got.

#2038 Fix name of AerSimulator generated by AerProvider
  qiskit_aer/aerprovider.py
  qiskit_aer/backends/aer_simulator.py
  releasenotes/notes/fix_aer_provider_backend-fef040819407bcca.yaml
  test/terra/backends/test_aer_provider.py
Labels: stable-backport-potential, Changelog: Bugfix

#2087 Adding ccz gate to statevector, unitary and tensor_network methods
  qiskit_aer/backends/backend_utils.py
  qiskit_aer/backends/statevector_simulator.py
  qiskit_aer/backends/unitary_simulator.py
  releasenotes/notes/support_ccz-2a1bb33ed9909a28.yaml
  src/framework/operations.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/tensor_network/tensor_net_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/aer_simulator/test_standard_gates.py
Labels: Changelog: New Feature

#2088 Add EstimatorV2
  qiskit_aer/primitives/__init__.py
  qiskit_aer/primitives/estimator_v2.py
  test/terra/primitives/test_estimator_v2.py
Labels: enhancement, Changelog: New Feature, automerge

#2081 Add build test for GPU
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  releasenotes/notes/add_gpu_build_test-2a95842b524c880b.yaml
Labels: stable-backport-potential, Changelog: New Feature
