Repository Qiskit/qiskit-aer, pull requests merged in 2024-05, with the labels that each got.

#2119 Fix issue 2084 again
  qiskit_aer/backends/aerbackend.py
  releasenotes/notes/fix_issue2084-632a829da1a8dfc5.yaml
  test/terra/primitives/test_sampler.py
Labels: stable-backport-potential, Changelog: Bugfix

#2138 Fix tests for the latest Qiskit
  test/terra/backends/aer_simulator/test_chunk.py
  test/terra/primitives/test_sampler_v2.py
  test/terra/states/test_aer_densitymatrix.py
  test/terra/states/test_aer_statevector.py
Labels: Changelog: Bugfix

#2109 Add simulator_metadata in metadata of SamplerV2
  qiskit_aer/primitives/sampler_v2.py
  releasenotes/notes/add_sampler_v2_simulator_metadata-e17850d483439f9a.yaml
Labels: stable-backport-potential, Changelog: Bugfix, automerge

#2146 Fix cuStateVec_enable option
  releasenotes/notes/fix_enabling_cuStateVec-1a2f1d3e35f3129d.yaml
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/unitary/unitary_state.hpp
Labels: stable-backport-potential, Changelog: Bugfix

#2147 Add support for rotation gates
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/backend_utils.py
  releasenotes/notes/add_rotation_support-c0ef8155a761e560.yaml
  src/framework/operations.hpp
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/extended_stabilizer/gates.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/statevector_state.hpp
  src/simulators/tensor_network/tensor_net_state.hpp
  src/simulators/unitary/unitary_state.hpp
  test/terra/backends/aer_simulator/test_control_flow.py
  test/terra/backends/aer_simulator/test_rotation.py
  test/terra/backends/test_parameterized_qobj.py
Labels: Changelog: New Feature

#2132 Fix deterministic measure of stabilizer
  releasenotes/notes/fix_stabilizer_measure-a06d761eba2546d2.yaml
  src/simulators/stabilizer/clifford.hpp
  test/terra/backends/aer_simulator/test_measure.py
Labels: stable-backport-potential, Changelog: Bugfix

#2120 Fix init of EstimatorV2 and SamplerV2
  README.md
  qiskit_aer/primitives/estimator_v2.py
  qiskit_aer/primitives/sampler_v2.py
  releasenotes/notes/fix_primitiveV2_init-afe7b331ddbef538.yaml
Labels: stable-backport-potential, Changelog: Bugfix

#2110 Fix deploy.yml
  .github/workflows/deploy.yml
Labels: stable-backport-potential, Changelog: Bugfix

#2137 Add support for ECR gate to MPS
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/backend_utils.py
  releasenotes/notes/add_ecr_to_mps-0eec56596fc486c7.yaml
  src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
  src/simulators/extended_stabilizer/gates.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  test/terra/backends/aer_simulator/test_cliffords.py
Labels: stable-backport-potential, Changelog: New Feature, Changelog: Bugfix

#2148 Handle gates with ctrl_stete=0
  qiskit_aer/backends/aer_compiler.py
  test/terra/backends/aer_simulator/test_cliffords.py
  test/terra/reference/ref_2q_clifford.py
Labels: stable-backport-potential, Changelog: New Feature

#2151 Fix random seed of unit tests
  test/terra/backends/test_parameterized_qobj.py
  test/terra/states/test_aer_densitymatrix.py
Labels: stable-backport-potential, Changelog: None
