Repository Qiskit/qiskit-aer, pull requests merged in 2024-01, with the labels that each got.

#2018 Deploy docs to GitHub Pages
  .github/workflows/docs-publish.yml
  tools/deploy_documentation.sh
  tools/rclone.conf.enc
Labels: automerge

#2024 Enable bit operations for boolean types
  src/framework/operations.hpp
  test/terra/backends/aer_simulator/test_control_flow.py
  test/terra/expression/test_classical_expressions.py
Labels: automerge

#1897 Add support for BLAS SVD functions in MPS simulation
  qiskit_aer/backends/aer_compiler.py
  qiskit_aer/backends/aer_simulator.py
  qiskit_aer/backends/qasm_simulator.py
  qiskit_aer/backends/wrappers/aer_controller_binding.hpp
  releasenotes/notes/compute-svd-with-lapack-3ee992d371d653d1.yaml
  src/framework/config.hpp
  src/framework/lapack_protos.hpp
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  src/simulators/matrix_product_state/matrix_product_state_internal.hpp
  src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
  src/simulators/matrix_product_state/svd.cpp
  src/simulators/matrix_product_state/svd.hpp
  test/terra/backends/aer_simulator/test_options.py
Labels: enhancement, performance

#1911 Parallelize sampling measurement in MPS
  releasenotes/notes/parallel-probabilistic-measurement-mps-ec00a896a0322213.yaml
  src/simulators/matrix_product_state/matrix_product_state.hpp
  src/simulators/matrix_product_state/matrix_product_state_internal.cpp
  test/terra/backends/aer_simulator/test_measure.py
Labels: performance

#2022 Add support for running with Python 3.12
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  constraints.txt
  pyproject.toml
  releasenotes/notes/add-py312-795ffe7d68f41c73.yaml
  setup.py
  tox.ini
Labels: Changelog: New Feature, automerge

#2026 Fixes of tests for the latest Qiskit
  releasenotes/notes/fix_for_daily_tests-3fa9df70fb3e53ee.yaml
  test/terra/noise/test_device_models.py
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential, Changelog: Deprecation, Changelog: Bugfix, automerge

#2034 Fix GPU wheel builds on release
  .github/workflows/deploy.yml
Labels: stable-backport-potential, Changelog: Bugfix

#2035 Fix test cases for Qiskit 0.45.2
  releasenotes/notes/fix_test_for_Qiskit0.45.2-e0544949be8e77fb.yaml
  test/benchmark/vqe_application.py
  test/terra/backends/aer_simulator/test_truncate.py
  test/terra/reference/ref_diagonal_gate.py
Labels: stable-backport-potential, Changelog: Deprecation

#2040 Remove remaining diagonal, isometry and uc
  test/terra/backends/aer_simulator/test_conditional.py
  test/terra/reference/ref_diagonal_gate.py
  test/terra/reference/ref_multiplexer.py
  test/terra/states/test_aer_state.py
  test/terra/states/test_aer_statevector.py
Labels: stable-backport-potential, Changelog: Deprecation, Changelog: None
