Repository Qiskit/qiskit-aer, pull requests merged in 2024-06, with the labels that each got.

#2159 Fix AerBackend.set_max_qubits
  qiskit_aer/backends/aerbackend.py
  releasenotes/notes/fix_AerBackend_set_max_qubits-fee8f0e104580e33.yaml
  test/terra/primitives/test_sampler.py
Labels: stable-backport-potential, Changelog: Bugfix

#2155 Add `BaseQuantumError` class
  qiskit_aer/backends/aerbackend.py
  qiskit_aer/noise/errors/base_quantum_error.py
  qiskit_aer/noise/errors/quantum_error.py
  qiskit_aer/noise/noise_model.py
  test/terra/noise/test_noise_model.py
Labels: Changelog: New Feature, automerge

#2156 Add optimized `PauliError` quantum error operator class
  qiskit_aer/noise/__init__.py
  qiskit_aer/noise/errors/__init__.py
  qiskit_aer/noise/errors/pauli_error.py
  releasenotes/notes/pauli-error-38fc637054cab207.yaml
  test/terra/backends/aer_simulator/test_noise.py
  test/terra/backends/aer_simulator/test_shot_branching.py
  test/terra/noise/test_noise_model.py
  test/terra/noise/test_pauli_error.py
  test/terra/reference/ref_pauli_noise.py
Labels: Changelog: New Feature

#2157 Pauli lindblad error
  qiskit_aer/noise/__init__.py
  qiskit_aer/noise/errors/__init__.py
  qiskit_aer/noise/errors/pauli_lindblad_error.py
  releasenotes/notes/pauli-lindblad-error-2fccae840ceec2aa.yaml
  src/noise/noise_model.hpp
  src/noise/quantum_error.hpp
  src/simulators/circuit_executor.hpp
  src/simulators/density_matrix/densitymatrix_executor.hpp
  src/simulators/density_matrix/densitymatrix_state.hpp
  src/simulators/matrix_product_state/svd.cpp
  src/simulators/parallel_state_executor.hpp
  src/simulators/stabilizer/pauli.hpp
  src/simulators/stabilizer/stabilizer_state.hpp
  src/simulators/statevector/statevector_executor.hpp
  src/simulators/statevector/statevector_state.hpp
  test/terra/backends/aer_simulator/test_noise.py
  test/terra/noise/test_noise_model.py
  test/terra/noise/test_pauli_lindblad_error.py
  test/terra/reference/ref_pauli_lindblad_noise.py
Labels: Changelog: New Feature

#2160 Updated documents and tutorials which supports Qiskit 1.0 and Primitives V2
  docs/tutorials/2_device_noise_simulation.ipynb
  docs/tutorials/3_building_noise_models.ipynb
  docs/tutorials/4_custom_gate_noise.ipynb
  docs/tutorials/5_noise_transformation.ipynb
  docs/tutorials/6_extended_stabilizer_tutorial.ipynb
  docs/tutorials/7_matrix_product_state_method.ipynb
  qiskit_aer/primitives/__init__.py
  setup.py
Labels: documentation

#2175 fix bit mapping inconsistency in inline of AerCompiler
  qiskit_aer/backends/aer_compiler.py
  releasenotes/notes/fix_inline_in_compiler-6ecdfcf38e2fa0c9.yaml
  test/terra/backends/aer_simulator/test_control_flow.py
Labels: stable-backport-potential, Changelog: Bugfix, automerge
